# Generated by Django 4.2.5 on 2024-01-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_realtor',
            new_name='is_dentist',
        ),
    ]
