# Generated by Django 4.2.5 on 2024-01-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_realtor_useraccount_is_dentist'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
