# Generated by Django 4.2.5 on 2024-02-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
